service : api

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
      

functions:
  get:
    handler: handler.get
    events:
      - http:
          path: /{id}
          method: get
          cors: true
  list:
    handler: handler.list
    events:
      - http:
          path: /
          method: get
          cors: true
  create:
    handler: handler.create
    events:
      - http:
          path: /
          method: post
          cors: true
  update:
    handler: handler.update
    events:
      - http:
          path: /{id}
          method: put
          cors: true
  delete:
    handler: handler.delete
    events:
      - http:
          path: /{id}
          method: delete
          cors: true
  